// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DemoApp.Data;

#nullable disable

namespace DemoApp.Migrations
{
    [DbContext(typeof(Data.DemoContext))]
    [Migration("20211129195634_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("demo_graphql.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Margaret Atwood"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Stephen King"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jane Austen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "George Orwell"
                        });
                });

            modelBuilder.Entity("demo_graphql.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            PublicationYear = 1985,
                            Title = "The Handmaid's Tale"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            PublicationYear = 1996,
                            Title = "Alias Grace"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            PublicationYear = 1977,
                            Title = "The Shining"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            PublicationYear = 1978,
                            Title = "The Stand"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 2,
                            PublicationYear = 1986,
                            Title = "It"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            PublicationYear = 1813,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 3,
                            PublicationYear = 1811,
                            Title = "Sense and Sensibility"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 3,
                            PublicationYear = 1816,
                            Title = "Emma"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 4,
                            PublicationYear = 1945,
                            Title = "Animal Farm"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 4,
                            PublicationYear = 1949,
                            Title = "Nineteen Eighty-Four"
                        });
                });

            modelBuilder.Entity("demo_graphql.Models.Book", b =>
                {
                    b.HasOne("demo_graphql.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
